### PR TITLE
Sniffer Plugin feedback fixes

### PR DESCRIPTION
**Pull request by larissa**
This MR includes the requested changes to the sniffer plugin.

### CODE REVIEW

**Comment by brauliobo** [comment]
@larissa the must be something wrong, as it seems the plugin is being readded, like af64990

**Comment by brauliobo** [comment]
@larissa yeah, commits are being added again, for example the "sniffer: Workaround for product category search to work on solr search". `git rebase` with `git rebase --skip` for commits already applied will help. that will make the review better

**Comment by larissa** [comment]
My bad, it was late at night :disappointed_relieved:

Should be easier to review now.

**Comment by brauliobo** [comment]
deployed :)

**Pull request merged**
